const std = @import("std");

const BuildMode = enum { nif_lib, sema };

// Helper to strip surrounding quotes from paths (needed for Windows paths with spaces)
fn stripQuotes(path: []const u8) []const u8 {
    if (path.len >= 2 and path[0] == '"' and path[path.len - 1] == '"') {
        return path[1 .. path.len - 1];
    }
    return path;
}

pub fn build(b: *std.Build) void {
    const resolved_target = b.standardTargetOptions(.{});
    const host_target = b.graph.host;
    const optimize = b.standardOptimizeOption(.{});

    // ERTS paths (auto-injected by zigler as -D flags)
    // stripQuotes handles Windows paths with spaces that are quoted on the command line
    const erts_include = stripQuotes(b.option([]const u8, "erts_include", "ERTS include path") orelse @panic("erts_include required"));
    const erl_nif_header = stripQuotes(b.option([]const u8, "erl_nif_header", "Path to erl_nif.h (or erl_nif_win.h on Windows)") orelse @panic("erl_nif_header required"));
    const erl_nif_win_path = stripQuotes(b.option([]const u8, "erl_nif_win_path", "Path to Windows erl_nif compatibility headers") orelse @panic("erl_nif_win_path required"));

    // Zigler paths (auto-injected by zigler as -D flags)
    const zigler_priv = stripQuotes(b.option([]const u8, "zigler_priv", "Zigler priv directory") orelse @panic("zigler_priv required"));
    const module_root = stripQuotes(b.option([]const u8, "module_root", "Module root directory") orelse @panic("module_root required"));

    const mode = b.option(BuildMode, "zigler-mode", "Build either the nif library or the sema analysis module") orelse .nif_lib;

    // Build paths using zigler_priv and module_root
    const beam_erl_nif_path = std.fs.path.join(b.allocator, &.{ zigler_priv, "beam/erl_nif.zig" }) catch @panic("OOM");
    const beam_path = std.fs.path.join(b.allocator, &.{ zigler_priv, "beam/beam.zig" }) catch @panic("OOM");
    const stub_erl_nif_path = std.fs.path.join(b.allocator, &.{ zigler_priv, "beam/stub_erl_nif.zig" }) catch @panic("OOM");
    const sema_path = std.fs.path.join(b.allocator, &.{ zigler_priv, "beam/sema.zig" }) catch @panic("OOM");

    // User's helper module is in build_files subdirectory
    const user_module_path = std.fs.path.join(b.allocator, &.{ module_root, "build_files/module.zig" }) catch @panic("OOM");

    // Generated nif file is in module_root
    const nif_path = std.fs.path.join(b.allocator, &.{ module_root, ".Elixir.ZiglerTest.CornerCases.BuildFilesOverrideTest.zig" }) catch @panic("OOM");

    switch (mode) {
        .nif_lib => {
            // Translate erl_nif.h to Zig module
            const erl_translate_c = b.addTranslateC(.{
                .root_source_file = .{ .cwd_relative = erl_nif_header },
                .target = resolved_target,
                .optimize = optimize,
                .link_libc = true,
            });
            erl_translate_c.addSystemIncludePath(.{ .cwd_relative = erts_include });
            erl_translate_c.addSystemIncludePath(.{ .cwd_relative = erl_nif_win_path });
            const erl_module = erl_translate_c.createModule();

            const erl_nif = b.createModule(.{
                .root_source_file = .{ .cwd_relative = beam_erl_nif_path },
                .imports = &[_]std.Build.Module.Import{},
                .link_libc = true,
            });

            erl_nif.addSystemIncludePath(.{ .cwd_relative = erts_include });
            erl_nif.addSystemIncludePath(.{ .cwd_relative = erl_nif_win_path });
            erl_nif.addImport("erl", erl_module);

            const beam = b.createModule(.{
                .root_source_file = .{ .cwd_relative = beam_path },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "erl_nif", .module = erl_nif },
                },
            });

            // attributes.zig is generated by zigler in the staging directory (local)
            const attributes = b.createModule(.{
                .root_source_file = .{ .cwd_relative = "attributes.zig" },
                .imports = &[_]std.Build.Module.Import{},
            });

            // User's helper module with add_one function
            const user_module = b.createModule(.{
                .root_source_file = .{ .cwd_relative = user_module_path },
                .imports = &[_]std.Build.Module.Import{},
            });

            // User's NIF code (generated by zigler from ~Z blocks)
            const nif = b.createModule(.{
                .root_source_file = .{ .cwd_relative = nif_path },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "erl_nif", .module = erl_nif },
                    .{ .name = "beam", .module = beam },
                    .{ .name = "attributes", .module = attributes },
                    .{ .name = "module", .module = user_module },
                },
                .link_libc = true,
            });

            // module.zig is generated by zigler in the staging directory (local)
            // This is the NIF shim with nif_init(), load(), etc.
            const nif_shim = b.createModule(.{
                .root_source_file = .{ .cwd_relative = "module.zig" },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "beam", .module = beam },
                    .{ .name = "erl_nif", .module = erl_nif },
                    .{ .name = "nif", .module = nif },
                },
                .target = resolved_target,
                .optimize = optimize,
            });

            const lib = b.addLibrary(.{
                .name = "Elixir.ZiglerTest.CornerCases.BuildFilesOverrideTest",
                .linkage = .dynamic,
                .version = .{ .major = 0, .minor = 16, .patch = 0 },
                .root_module = nif_shim,
            });

            lib.linker_allow_shlib_undefined = true;
            lib.use_llvm = true;

            b.installArtifact(lib);
        },
        .sema => {
            const erl_nif = b.createModule(.{
                .root_source_file = .{ .cwd_relative = stub_erl_nif_path },
                .imports = &[_]std.Build.Module.Import{},
            });

            const beam = b.createModule(.{
                .root_source_file = .{ .cwd_relative = beam_path },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "erl_nif", .module = erl_nif },
                },
            });

            // attributes.zig is generated by zigler in the staging directory (local)
            const attributes = b.createModule(.{
                .root_source_file = .{ .cwd_relative = "attributes.zig" },
                .imports = &[_]std.Build.Module.Import{},
            });

            // User's helper module with add_one function
            const user_module = b.createModule(.{
                .root_source_file = .{ .cwd_relative = user_module_path },
                .imports = &[_]std.Build.Module.Import{},
            });

            // User's NIF code (generated by zigler from ~Z blocks)
            const nif = b.createModule(.{
                .root_source_file = .{ .cwd_relative = nif_path },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "erl_nif", .module = erl_nif },
                    .{ .name = "beam", .module = beam },
                    .{ .name = "attributes", .module = attributes },
                    .{ .name = "module", .module = user_module },
                },
                .link_libc = true,
            });

            const sema = b.createModule(.{
                .root_source_file = .{ .cwd_relative = sema_path },
                .imports = &[_]std.Build.Module.Import{
                    .{ .name = "nif", .module = nif },
                },
                .target = host_target,
                .optimize = optimize,
            });

            const sema_exe = b.addExecutable(.{
                .name = "sema",
                .root_module = sema,
            });

            b.installArtifact(sema_exe);

            const sema_run_cmd = b.addRunArtifact(sema_exe);
            if (b.args) |args| sema_run_cmd.addArgs(args);
            const sema_step = b.step("sema", "Run sema");
            sema_step.dependOn(&sema_run_cmd.step);
        },
    }
}
