name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4
    - name: Download Zig
      run: |
        wget https://ziglang.org/download/0.14.0/zig-0.14.0.tar.xz
        tar -xf zig-0.14.0.tar.xz

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y erlang-runtime27
          pkg install -y elixir-devel

          # see: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=284533
          cat /etc/ssl/certs/*.0 > /etc/ssl/cert.pem

        run: |
          PATH=$PATH:/usr/local/lib/erlang27/bin
          ls -laF

          # mix local.hex --force
          # mix deps.get
          # mix test --exclude no_ci