name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-20.04
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y elixir-devel

        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          sysctl hw.model
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem