name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      id: zig-cache
      with:
        path: zig-0.14.0.tar.xz
        key: ${{ hashFiles('zig-0.14.0/**/*') }}

    - name: Install llvm
      run: |
        sudo apt-get install clang-19
        sudo apt-get install lld-19
        sudo apt-get install libclang-dev
        sudo apt-get install llvm-19-dev

    - name: Download Zig
      run: |
        if [ ! -f zig-0.14.0.tar.xz ]; then
          wget https://ziglang.org/download/0.14.0/zig-0.14.0.tar.xz
          tar -xf zig-0.14.0.tar.xz
        fi

        mkdir -p zig-0.14.0/build
        cd zig-0.14.0/build
        cmake ..
        make install

    - uses: erlef/setup-beam@v1
      name: Setup Erlang
      with:
        otp-version: '27.3'
        elixir-version: '1.18.3'

    - uses: actions/cache@v3
      id: deps-cache
      with:
        path: deps
        key: mix-${{ hashFiles('/mix.lock') }}

    - name: get deps
      run: mix deps.get

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y erlang-runtime27
          pkg install -y elixir-devel

          # see: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=284533
          cat /etc/ssl/certs/*.0 > /etc/ssl/cert.pem

        run: |
          PATH=$PATH:/usr/local/lib/erlang27/bin
          PWD=`pwd`
          ZIG_ARCHIVE_PATH="$PWD/zig-0.14.0.tar.xz"

          mix local.hex --force
          mix compile
          mix test --exclude no_ci