name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      name: Setup Erlang
      with:
        otp-version: '27.3'
        elixir-version: '1.18.3'

    - uses: actions/cache@v3
      id: deps-cache
      with:
        path: deps
        key: mix-${{ hashFiles('/mix.lock') }}

    - name: get deps
      run: mix deps.get

    - uses: actions/cache@v3
      id: zig-cache
      with:
        path: zig
        key: zig-freebsd

    - name: get zig
      run: |
        if [ ! -d zig ]; then
          git clone -b 0.14.0 https://github.com/ziglang/zig.git
        fi 

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y erlang-runtime27
          pkg install -y elixir-devel
          pkg install -y llvm19
          pkg install -y cmake zstd ninja

          ldconfig /usr/local/lib

        run: |
          cd zig
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_PREFIX_PATH=/usr/local/llvm19/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib" -DZIG_BUILD_MODE=ReleaseSafe
          ninja zig1

          mv zig1 zig
          export ZIG_ARCHIVE_PATH=`pwd`

          cd ..
          mix test --exclude no_ci