name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      name: Setup Erlang
      with:
        otp-version: '27.3'
        elixir-version: '1.18.3'

    - uses: actions/cache@v3
      id: deps-cache
      with:
        path: deps
        key: mix-${{ hashFiles('/mix.lock') }}

    - name: get deps
      run: mix deps.get

    - uses: actions/cache@v3
      id: zig-cache
      with:
        path: zig
        key: zig-freebsd

    - name: get zig
      run: |
        if [ ! -d zig ]; then
          git clone -b 0.14.0 https://github.com/ziglang/zig.git
        fi 

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y erlang-runtime27
          pkg install -y elixir-devel
          pkg install -y llvm19
          pkg install -y ca_root_nss

          pkg install -y cmake zstd libxml2 lzma ninja

          ldconfig /usr/local/lib

        run: |
          cd zig
          mkdir build
          cd build
          cmake .. -G Ninja -DZIG_STATIC_LLVM=ON -DCMAKE_PREFIX_PATH="/usr/local/llvm19;/usr/local" -DCMAKE_BUILD_TYPE=ReleaseSafe
          ninja -C build

          zig version

          export ZIG_EXECUTABLE_PATH="$(pwd)/zig"
          export PATH="/usr/local/lib/erlang27/bin:$PATH"
          export SSL_CACERTFILE=/usr/local/etc/ssl/cert.pem
          export CI_LOG_LEVEL=debug

          cd ../..

          mix local.hex --force

          mix test --exclude no_ci
