name: Elixir CI - FreeBSD

on: push

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD / Elixir
    steps:
    - uses: actions/checkout@v4

    - uses: erlef/setup-beam@v1
      name: Setup Erlang
      with:
        otp-version: '27.3'
        elixir-version: '1.17.3'

    - uses: actions/cache@v3
      id: deps-cache
      with:
        path: deps
        key: mix-${{ hashFiles('mix.lock') }}

    - name: get deps
      run: mix deps.get

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        mem: 8192
        usesh: true
        prepare: |
          pkg install -y erlang-runtime28
          pkg install -y elixir
          pkg install -y ca_root_nss

          # Download prebuilt Zig 0.16.0 for FreeBSD
          fetch https://ziglang.org/download/0.16.0/zig-x86_64-freebsd-0.16.0.tar.xz
          tar -xJf zig-x86_64-freebsd-0.16.0.tar.xz
          mv zig-x86_64-freebsd-0.16.0 /usr/local/zig

        run: |
          export ZIG_EXECUTABLE_PATH="/usr/local/zig/zig"
          export PATH="/usr/local/lib/erlang28/bin:$PATH"
          export SSL_CACERTFILE=/usr/local/etc/ssl/cert.pem

          mix local.hex --force

          mix test --exclude no_ci --exclude skip_freebsd
