name: Elixir CI - Linux

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    name: Linux OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '27.3'
            elixir-version: '1.18.3'
          - otp-version: '27.3'
            elixir-version: '1.17.3'
          - otp-version: '26.2'
            elixir-version: '1.16.3'
          - otp-version: '25.3'
            elixir-version: '1.15.8'
          - otp-version: '24.3'
            elixir-version: '1.14.5'
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}

    - uses: actions/cache@v3
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ matrix.pair.otp-version }}-${{ matrix.pair.elixir-version }}-${{ hashFiles('/mix.lock') }}-${{ hashfiles('installer/**/*') }}

    - name: Install ZIGLER_TEST_BLAS
      run: sudo apt install -y libopenblas-dev

    - name: Install dependencies
      run: mix deps.get

    - uses: actions/cache@v3
      id: build-cache
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.pair.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('/mix.lock') }}

    - name: Compile base
      run: mix compile

    - name: Get Zig version
      id: zig-version
      run: mix eval "IO.puts(Zig.version())"

    - uses: actions/cache@v3
      id: zig-cache
      with:
        path: zig
        key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.stdout }}

    - name: Get Zig
      run: mix zig.get

    - name: Run Tests
      env:
        RUNNING_CI: "TRUE"
        ZIGLER_TEST_BLAS: "TRUE"
      run: mix test --exclude no_ci
