name: Elixir CI - Windows

on: push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'  # adjust as needed
          otp-version: '27.3'       # adjust as needed

      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('/mix.lock') }}-${{ hashfiles('/installer/**/*') }}
  
      - name: Install dependencies
        run: mix deps.get
  
      - uses: actions/cache@v3
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('/mix.lock') }}
  
      - name: Compile base
        run: mix compile
  
      - name: Get Zig version
        id: zig-version
        shell: bash
        run: | 
          VERSION=$(mix eval "IO.puts(Zig.version())" | tail -n 1)
          echo "zig_version=$VERSION" >> $GITHUB_OUTPUT
  
      - uses: actions/cache@v3
        id: zig-cache
        with:
          path: zig
          key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.zig_version }}
  
      - name: Get Zig
        run: mix zig.get

      - name: Run Tests
        env:
          RUNNING_CI: "TRUE"
        run: mix test --exclude no_ci --trace